config/routes.rb
Sproutzly::Application.routes.draw do

  root :to => 'homes#index'
  match 'addon' => 'addon#index'
  resources :addons
  match 'setting' => 'setting#index'
  resources :settings
  match 'dashboard' => 'dashboard#index'
  match 'register' => 'users#new'
  resources :sessions
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'
  resources :users
  resources :works
  resources :influencers
  match 'library' => 'library#index', :as => :library
  match 'subscribe' => 'homes#subscribe'

  namespace :admin do
    root :to => 'dashboards#index'
    match 'login' => 'sessions#new'
    match 'logout' => 'sessions#destroy'
    resources :sessions
    resources :works
    resources :billings
    resources :influencers
  end

end

app/models/influencer.rb
class Influencer
  include Mongoid::Document
  field :first_name, type: String
  field :last_name, type: String
  field :market_id, type: String
  field :image_url, type: String
  field :company, type:String
  field :twitter_url, type: String
  field :facebook_url, type: String
  field :blog_url, type: String

  belongs_to :market, :foreign_key => "market_id"

  def t
    Influencer.create!(
      first_name: "",
      last_name: "",
      image_url: "",
      company: "",
      twitter_url: "",
      facebook_url: "",
      blog_url: ""
    )
  end
end

app/controllers/influencers_controller.rb
class InfluencersController < ApplicationController
  # GET /influencers
  # GET /influencers.json
  def index
    if(params[:market_id])
      #@influencers = Influencer.where(:market_id => params[:market_id]).take(4)
      @influencers = Market.find(params[:market_id]).influencers.limit(4)
    else
      @influencers = Influencer.all
    end

    respond_to do |format|
      #format.html # index.html.erb
      format.json { render json: @influencers }
    end
  end

  # GET /influencers/1
  # GET /influencers/1.json
  def show
    @influencer = Influencer.find(params[:id])

    respond_to do |format|
      format.html { render action: 'show', layout: nil }
      format.json { render json: @influencer }
    end
  end

  # GET /influencers/new
  # GET /influencers/new.json
  def new
    @influencer = Influencer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @influencer }
    end
  end

  # GET /influencers/1/edit
  def edit
    @influencer = Influencer.find(params[:id])
  end

  # POST /influencers
  # POST /influencers.json
  def create
    @influencer = Influencer.new(params[:influencer])

    respond_to do |format|
      if @influencer.save
        format.html { redirect_to @influencer, notice: 'Influencer was successfully created.' }
        format.json { render json: @influencer, status: :created, location: @influencer }
      else
        format.html { render action: "new" }
        format.json { render json: @influencer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /influencers/1
  # PUT /influencers/1.json
  def update
    @influencer = Influencer.find(params[:id])

    respond_to do |format|
      if @influencer.update_attributes(params[:influencer])
        format.html { redirect_to @influencer, notice: 'Influencer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @influencer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /influencers/1
  # DELETE /influencers/1.json
  def destroy
    @influencer = Influencer.find(params[:id])
    @influencer.destroy

    respond_to do |format|
      format.html { redirect_to influencers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/influencers_helper.rb
module InfluencersHelper
end

app/views/influencers/_form.html.erb
<%= form_for(@influencer) do |f| %>
  <% if @influencer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@influencer.errors.count, "error") %> prohibited this influencer from being saved:</h2>

      <ul>
      <% @influencer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/influencers/_influencer.html.erb
<div class="inf-item">
	<%= image_tag influencer.image_url, :class => "pic" %>
	<br />
	<p class="name"><%= "#{influencer.first_name} #{influencer.last_name}" %></p>
	<p class="company"><%= influencer.company %></p>
	<% if(influencer.twitter_url) %>
		<a href="<%= influencer.twitter_url %>" target="_blank">
			<%= image_tag "home/twitterCircle.png", :class => "social-icon" %>
		</a>
	<% end %>
	<% if(influencer.facebook_url) %>
		<a href="<%= influencer.facebook_url %>" target="_blank">
			<%= image_tag "home/facebookCircle.png", :class => "social-icon" %>
		</a>
	<% end %>
	<% if(influencer.blog_url) %>
		<a href="<%= influencer.blog_url %>" target="_blank">
			<%= button_tag "Blog", :class => "btn btn-info" %>
		</a>
	<% end %>
	<br /><br />
	<%= button_tag "ADVICE", :class => "btn-select-advice-influencer btn btn-advice", :data => {:id => influencer.id} %>
	<% if(influencer.twitter_url) %>
		<%= button_tag "TWEET", :class => "btn-select-tweet-influencer btn btn-tweet", :data => {:id => influencer.id} %>
	<% end %>
	<% if(influencer.blog_url) %>
		<%= button_tag "POST", :class => "btn-select-tweet-influencer btn btn-post", :data => {:id => influencer.id} %>
	<% end %>

</div>

app/views/influencers/edit.html.erb
<h1>Editing influencer</h1>

<%= render 'form' %>

<%= link_to 'Show', @influencer %> |
<%= link_to 'Back', influencers_path %>

app/views/influencers/index.html.erb
<h1>Listing influencers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @influencers.each do |influencer| %>
  <tr>
    <td><%= link_to 'Show', influencer %></td>
    <td><%= link_to 'Edit', edit_influencer_path(influencer) %></td>
    <td><%= link_to 'Destroy', influencer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Influencer', new_influencer_path %>

app/views/influencers/new.html.erb
<h1>New influencer</h1>

<%= render 'form' %>

<%= link_to 'Back', influencers_path %>

app/views/influencers/show.html.erb
<%= render 'influencer', :influencer => @influencer %>