config/routes.rb
Sproutzly::Application.routes.draw do

  root :to => 'homes#index'
  match 'addon' => 'addon#index'
  resources :addons
  match 'setting' => 'setting#index'
  resources :settings
  match 'dashboard' => 'dashboard#index'
  match 'register' => 'users#new'
  resources :sessions
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'
  resources :users
  resources :works
  resources :influencers
  match 'library' => 'library#index', :as => :library
  match 'subscribe' => 'homes#subscribe'

  namespace :admin do
    root :to => 'dashboards#index'
    match 'login' => 'sessions#new'
    match 'logout' => 'sessions#destroy'
    resources :sessions
    resources :works
    resources :billings
    resources :influencers
  end

end

app/controllers/addons_controller.rb
class AddonsController < ApplicationController
  # GET /addons
  # GET /addons.json
  def index

    respond_to do |format|
      format.html # index.html.erb
    end
  end

end

app/helpers/addons_helper.rb
module AddonsHelper
end

app/views/addons/_form.html.erb
<%= form_for(@addon) do |f| %>
  <% if @addon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@addon.errors.count, "error") %> prohibited this addon from being saved:</h2>

      <ul>
      <% @addon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addons/edit.html.erb
<h1>Editing addon</h1>

<%= render 'form' %>

<%= link_to 'Show', @addon %> |
<%= link_to 'Back', addons_path %>

app/views/addons/index.html.erb
<div id="addon" class="container">

  <h1>Grow Even More</h1>

  <p>Get additional ways to boost your brand.</p>

  <div class="addonRow row">
    <div class="block span4">
      <%= image_tag "addons/youtube.png", :style => "width:120px" %>
      <h2>200 Youtube Likes</h2>
      <button type="button" class="btn btn-primary btn-large">Get It</button>
    </div>

    <div class="block span4">
      <%= image_tag "addons/pintrest.jpg", :style => "width:120px" %>
      <h2>300 Pins</h2>
      <button type="button" class="btn btn-primary btn-large">Get It</button>
    </div>

    <div class="block span4">
      <%= image_tag "addons/twitter.png",  :style => "width:120px"%>
      <h2>Twitter Party</h2>
      <button type="button" class="btn btn-primary btn-large">Get It</button>
    </div>
  </div>

  <div class="addonRow row">
    <div class="block span4">
      <%= image_tag "home/influenceCircle.png" %>
      <h2>Access Influences</h2>
      <button type="button" class="btn btn-primary btn-large">Get It</button>
    </div>

    <div class="block span4">
      <%= image_tag "home/growthCircle.png",  :style => "width:108px"%>
      <h2>1 Growth Strategy</h2>
      <button type="button" class="btn btn-primary btn-large">Get It</button>
    </div>

    <div class="block span4">
      <%= image_tag "addons/instagram.jpeg",  :style => "width:120px"%>
      <h2>500 Likes</h2>
      <button type="button" class="btn btn-primary btn-large">Get It</button>
    </div>
  </div>


</div>

app/views/addons/new.html.erb
<h1>New addon</h1>

<%= render 'form' %>

<%= link_to 'Back', addons_path %>

app/views/addons/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_addon_path(@addon) %> |
<%= link_to 'Back', addons_path %>