config/routes.rb
Sproutzly::Application.routes.draw do

  root :to => 'homes#index'
  match 'addon' => 'addon#index'
  resources :addons
  match 'setting' => 'setting#index'
  resources :settings
  match 'dashboard' => 'dashboard#index'
  match 'register' => 'users#new'
  resources :sessions
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'
  resources :users
  resources :works
  resources :influencers
  match 'library' => 'library#index', :as => :library
  match 'subscribe' => 'homes#subscribe'

  namespace :admin do
    root :to => 'dashboards#index'
    match 'login' => 'sessions#new'
    match 'logout' => 'sessions#destroy'
    resources :sessions
    resources :works
    resources :billings
    resources :influencers
  end

end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::AdminController
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
		unless(current_user)
			redirect_to root_url
			return
		end

		@works = current_user.works.all
		if(@works)
			@twitter_work_item = @works.select { |w| w.type_id == WorkType.TWITTER_FOLLOWERS }.first
			@facebook_work_item = @works.select { |w| w.type_id == WorkType.FACEBOOK_FANS }.first
			@influencer_work_item = @works.select { |w| w.type_id == WorkType.INFLUENCER }.first
			@growth_work_item = @works.select { |w| w.type_id == WorkType.GROWTH }.first
		end

		@markets = Market.all
		
		respond_to do |format|
			format.html
		end
	end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/admin/dashboards/index.html.erb
<h1>Admin Dashboard</h1>
<div id="admin-dashboard" class="row-fluid">
  
    <div class="span4 dash-item">
      <a href="<%= admin_works_path %>">
      <%= image_tag "illustrations/mail.png", :class => "big-illustration-pusher" %>
      <h2>Work Orders</h2>
      </a>
    </div>
  
    <div class="span4 dash-item">
      <a href="<%= admin_billings_path %>">
      <%= image_tag "illustrations/clipboard.png", :class => "big-illustration-pusher" %>
      <h2>Billings</h2>
      </a>
    </div>
  
  
  <div class="span4 dash-item">
    <a href="<%= admin_influencers_path %>">
    <!-- <a href="<%= admin_influencers_path %>"> -->
      <span class="gicon fui-man-24"></span>
      <h2>Influencers</h2>
    <!-- </a> -->
    </a>
  </div>
  
</div>