config/routes.rb
Sproutzly::Application.routes.draw do

  root :to => 'homes#index'
  match 'addon' => 'addon#index'
  resources :addons
  match 'setting' => 'setting#index'
  resources :settings
  match 'dashboard' => 'dashboard#index'
  match 'register' => 'users#new'
  resources :sessions
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'
  resources :users
  resources :works
  resources :influencers
  match 'library' => 'library#index', :as => :library
  match 'subscribe' => 'homes#subscribe'

  namespace :admin do
    root :to => 'dashboards#index'
    match 'login' => 'sessions#new'
    match 'logout' => 'sessions#destroy'
    resources :sessions
    resources :works
    resources :billings
    resources :influencers
  end

end

app/models/influencer.rb
class Influencer
  include Mongoid::Document
  field :first_name, type: String
  field :last_name, type: String
  field :market_id, type: String
  field :image_url, type: String
  field :company, type:String
  field :twitter_url, type: String
  field :facebook_url, type: String
  field :blog_url, type: String

  belongs_to :market, :foreign_key => "market_id"

  def t
    Influencer.create!(
      first_name: "",
      last_name: "",
      image_url: "",
      company: "",
      twitter_url: "",
      facebook_url: "",
      blog_url: ""
    )
  end
end

app/models/market.rb
class Market
  include Mongoid::Document
  field :name, type: String
  field :desc, type: String

  has_many :influencers, :foreign_key => "market_id"
end

app/models/newsletter_contact.rb
class NewsletterContact
  include Mongoid::Document
  field :email, type: String
end

app/models/notifier.rb
class Notifier < ActionMailer::Base
  default :from => "team@sproutzly.com"

  # send a signup email to the user, pass in the user object that contains the user's email address
  def signup_email(user)
    mail( :to => user.email, :subject => "Thanks for signing up" )
  end

  def newsletter_thanks(email)
    mail( :to => email, :subject => "Newsletter Confirmation" )
  end
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
class User
  include Mongoid::Document
  field :email, type: String
  field :password, type: String
  field :password_confirmation, type: String
  field :twitter_handle, type: String
  field :facebook_url, type: String
  field :website, type: String
  field :last_login, type: Date

  validates_uniqueness_of :email, message: 'Email is already taken'
  validates_presence_of :email, message: 'Email is required'
  validates_presence_of :website, message: 'Website is required'
  validates :password, :presence =>true, :length => { :minimum => 6, :maximum => 12 }, :confirmation =>true#, message: 'Password is required'
  validates_confirmation_of :password, message: 'Password Confirmation Mismatch' 
  validates :email, allow_blank: false, format: {
    with: /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i,
    message: 'Email is invalid'
  }
  validates_format_of :website, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix, message: 'Website is Invalid'

  embeds_many :works

end

app/models/work.rb
class Work
  include Mongoid::Document
  field :status_id, type: Integer
  field :assigned_to, type: String
  field :value, type: String
  field :type_id, type: Integer
  field :type_desc, type: String
  field :note, type: String

  embedded_in :user

  #validates_presence_of :status_id
  validates_presence_of :type_id

  def update_to_created
  	self.status_id = 0
  end

  def update_to_in_progress
		self.status_id = 1
  end

  def update_to_done
		self.status_id = 2
  end

  def in_progress?
  	self.status_id == 1
  end

  def done?
  	self.status_id == 2
  end
end

app/models/work_type.rb
class WorkType

	def self.TWITTER_FOLLOWERS() 1 end
	def self.FACEBOOK_FANS() 2 end
	def self.INFLUENCER() 3 end
	def self.GROWTH() 4 end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    respond_to do |format|
      format.html { render action: "index", layout: 'blank' }
    end
  end

  def subscribe
  	NewsletterContact.create!(email: params[:email])
  	Notifier.newsletter_thanks(params[:email])

  	respond_to do |format|
      format.json { render json: true }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html { render action: "new", layout: nil }
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:current_user_id] = @user.id
        format.html { redirect_to dashboard_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created }#, location: @user 
      else
        format.html { render action: "new" }
        format.json { render :json => { :errors => @user.errors.full_messages }, 
          status: :unprocessable_entity }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

# GET /users
# GET /users.json
# def index
#   @users = User.all

#   respond_to do |format|
#     format.html # index.html.erb
#     format.json { render json: @users }
#   end
# end

# GET /users/1
# GET /users/1.json
# def show
#   @user = User.find(params[:id])

#   respond_to do |format|
#     format.html # show.html.erb
#     format.json { render json: @user }
#   end
# end

# DELETE /users/1
# DELETE /users/1.json
# def destroy
#   @user = User.find(params[:id])
#   @user.destroy

#   respond_to do |format|
#     format.html { redirect_to users_url }
#     format.json { head :no_content }
#   end
# end

app/helpers/addons_helper.rb
module AddonsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/influencers_helper.rb
module InfluencersHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head prefix="og: http://ogp.me/ns# getgumball: 
                http://ogp.me/ns/apps/getgumball#">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sproutzly | Get Growing" %></title>
    <meta name="keywords" content="Grow Company,Buy Followers,Buy Likes,Buy Influence, Growth Hacking, Growth Services">
    <meta name="description" content="Sproutzly gets your brand or business essential exposure, influence, and growth.">
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= render 'shared/favicons' %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :head %>
    <%#= render 'shared/ga' %>
  </head>
  <body class="admin">
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_url %>">
            <%= image_tag("logos/logo_horiz.png", :class => "main-logo") %>
          </a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
            </ul>
            <ul class="nav pull-right"> 
              <!-- <li><%#= link_to "Settings", "/settings", :class => "nl"  %></li> -->
              <!-- <li><%#= link_to "Link2", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li> -->
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <%= bootstrap_flash %>
      <%= yield %>
      <footer>
        <p>&copy;Sproutzly 2013</p>
      </footer>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= render 'shared/inline_global_js' %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head prefix="og: http://ogp.me/ns# getgumball:
                http://ogp.me/ns/apps/getgumball#">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sproutzly | Get Growing" %></title>
    <meta name="keywords" content="Grow Company,Buy Followers,Buy Likes,Buy Influence, Growth Hacking, Growth Services">
    <meta name="description" content="Sproutzly gets your brand or business essential exposure, influence, and growth.">
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%#= render 'shared/favicons' %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :head %>
    <%#= render 'shared/ga' %>
  </head>
  <body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div class="navbar navbar-header navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= dashboard_url %>">
            <%= image_tag("logos/logo_horiz.png", :class => "main-logo") %>
          </a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
            </ul>
            <ul class="nav pull-right">
              <% if(current_user) %>
                <li><%= link_to "Addons", addons_path  %></li>
                <li><%= link_to "Settings", "/settings", :class => "nl"  %></li>
                <li><%= link_to "Logout", logout_path, :class => "nl" %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

    <%= render 'shared/footer' %>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= render 'shared/inline_global_js' %>
    <%= javascript_include_tag "application" %>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
  </body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sproutzly | Get Growing" %></title>
    <meta name="keywords" content="Grow Company,Buy Followers,Buy Likes,Buy Influence, Growth Hacking, Growth Services">
    <meta name="description" content="Sproutzly gets your brand or business essential exposure, influence, and growth.">
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%#= render 'shared/favicons' %>

    <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>

    <script type="text/javascript" src="//use.typekit.net/tvt4sfp.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= yield :head %>
    <%#= render 'shared/ga' %>
  </head>
  <body>
    <%= yield %>
    <%= render 'shared/footer' %>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= render 'shared/inline_global_js' %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shared/_favicons.html.erb
<!-- For third-generation iPad with high-resolution Retina display: -->
<!-- Size should be 144 x 144 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

<!-- For iPhone with high-resolution Retina display: -->
<!-- Size should be 114 x 114 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

<!-- For first- and second-generation iPad: -->
<!-- Size should be 72 x 72 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<!-- Size should be 57 x 57 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

<!-- For all other devices -->
<!-- Size should be 32 x 32 pixels -->
<%= favicon_link_tag '/favicon.ico', :rel => 'icon' %>
<%= favicon_link_tag '/favicon.ico', :rel => 'shortcut icon' %>

app/views/shared/_footer.html.erb
<footer>
  <div class="navbar navbar-fluid-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%= root_url %>">
        </a>
        <div class="container-fluid nav-collapse">
          <ul class="nav">
            <li><%= link_to "Terms & Conditions", "#", :class => "nl"  %></li>
            <li><%= link_to "Privacy Policy", "#", :class => "nl" %></li>
          </ul>
          <ul class="nav pull-right">

            <li>

              <div class="footer-btn-twitter-fb footer-btn-twitter-fb-spacer">
                <a href="https://twitter.com/sproutzly" class="twitter-follow-button" data-show-count="true">Follow @sproutzly</a>
              </div>
            </li>

            <li>
              <div class="footer-btn-twitter-fb fb-like" data-href="http://www.facebook.com/Sproutzly" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
            </li>

            <!--<li><%#= link_to "Link3", "/path3"  %></li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
</footer>

app/views/shared/_inline_global_js.html.erb
<script type="text/javascript">
	var logged_in = <%= (current_user) ? "true" : "false" %>;
</script>